shared/gatt-db: Prepare Write req error BT_ATT_ERROR_UNLIKELY
Fixes Prepare Write req error: BT_ATT_ERROR_UNLIKELY

    ATT: Error (0x01)
      Error: Unlikely error (14)
      Prepare Write req (0x16) on handle 0x0069

The prep_write_complete_cb was not getting called
The attrib->write_func code block does not need to be called when len is 0